language: node_js
node_js:
  - "node"
  - "lts/*"
services:
  - postgresql
before_install:
  - psql -c 'create database sources;' -U postgres
  - psql -c 'create database sources-test;' -U postgres
before_script:
  - yarn build