version: '2'
services:
  web:
    build: .
    image: sources
    restart: always
    command: yarn start
    ports:
    - "3000:3000"
    depends_on:
    - database
    env_file: .env
    environment:
    - DATABASE_USER=sources
    - DATABASE_PASSWORD=sources
    - DATABASE_HOST=database
  database:
    image: postgres:latest@sha256:8b40dc8680882be54428e8baba33f0514b4c92e91dc60ca21c9d81a9a926c2d2
    restart: always
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_USER=sources
    - POSTGRES_PASSWORD=sources
    - POSTGRES_DB=sources
