version: '2'
services:
  web:
    build: .
    image: sources
    restart: always
    command: npm start
    ports:
    - "3000:3000"
    depends_on:
    - database
    env_file: .env
    environment:
    - DATABASE_USER=sources
    - DATABASE_PASSWORD=sources
    - DATABASE_HOST=database
  database:
    image: postgres:latest@sha256:e6708d2202efbeada699821bafb710365d6d13d61ab5d838a015d3acd08d6f7e
    restart: always
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_USER=sources
    - POSTGRES_PASSWORD=sources
    - POSTGRES_DB=sources
